version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules/
    links:
      - db
      - cache
    command: tail -F /dev/null
    environment:
      PORT: 8000
      TOKEN_SECRET: 724b110eced76bf20851e0187bbbc180mdore4c6e3b0771ae76eb6244537a969b2f777be433cc9ce40c202607d4defb1b3d4a0223388e5630b6beaa0f52e6a76
      DB_USER: postgres
      DB_HOST: db
      DB: blog
      DB_PASSWORD: mysecretpassword
      DB_PORT: 5432
      CACHE_HOST: cache
      CACHE_PORT: 6379
      AWS_ACCESS_KEY_ID: ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: SECRET_ACCESS_KEY
      AWS_BUCKET_NAME: blog-avatars
      AWS_REGION: eu-central-1
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "blog"
      POSTGRES_PASSWORD: mysecretpassword
  cache:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - ./cacheVolume:/data
    command: redis-server --requirepass mysecretpassword --save 60 1 --loglevel warning
