{
 "title": "Blog API dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Number of Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{code=~\"4.*\"}[1m]))",
     "legendFormat": "4xx errors"
    },
    {
     "expr": "sum(increase(http_request_duration_ms_count{code=~\"5.*\"}[1m]))",
     "legendFormat": "5xx errors"
    }
   ]
  },
  {
   "title": "90th 95th 99th Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_ms_bucket[1m])) by (le, route, method))",
     "legendFormat": "90th {{method}} {{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_ms_bucket[1m])) by (le, route, method))",
     "legendFormat": "95th {{method}} {{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_ms_bucket[1m])) by (le, route, method))",
     "legendFormat": "99th {{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Requests Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{code=~\"2.*\"}[1m])) by (route, method)",
     "legendFormat": "2xx {{method}} {{route}}"
    },
    {
     "expr": "sum(increase(http_request_duration_ms_count{code=~\"4.*\"}[1m])) by (route, method)",
     "legendFormat": "4xx {{method}} {{route}}"
    },
    {
     "expr": "sum(increase(http_request_duration_ms_count{code=~\"5.*\"}[1m])) by (route, method)",
     "legendFormat": "5xx {{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Number of Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count[1m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(http_request_duration_ms_sum[$__range]) / rate(http_request_duration_ms_count[$__range])) by (route, method)",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Number of 200 OK vs Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{code=~\"2.*\"}[1m]))",
     "legendFormat": "Valid requests"
    },
    {
     "expr": "sum(increase(http_request_duration_ms_count{code!~\"2.*\"}[1m]))",
     "legendFormat": "Error requests"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{app=\"blog-api\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}