CREATE TABLE users (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  email VARCHAR(50) UNIQUE NOT NULL,
  password CHAR(60) NOT NULL,
  fullName VARCHAR(100) NOT NULL,
  about TEXT,
  createdOn TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() AT TIME ZONE 'utc') NOT NULL
);

CREATE TYPE POST_STATUS as ENUM ('PUBLISHED', 'DRAFT');

CREATE TABLE posts (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  userId INT REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(250) NOT NULL,
  status POST_STATUS DEFAULT 'DRAFT' NOT NULL,
  fullName TEXT NOT NULL,
  createdOn TIMESTAMP NOT NULL
);