CREATE TABLE users (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  email VARCHAR(50) UNIQUE NOT NULL,
  password CHAR(60) NOT NULL,
  fullname VARCHAR(100) NOT NULL,
  about TEXT,
  createdon DATE DEFAULT now() NOT NULL
);

CREATE TYPE POST_STATUS as ENUM ('PUBLISHED', 'DRAFT');

CREATE TABLE posts (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  userid INT REFERENCES users(id) ON DELETE CASCADE NOT NULL ,
  title VARCHAR(250) NOT NULL,
  status POST_STATUS DEFAULT 'DRAFT' NOT NULL,
  body TEXT NOT NULL,
  createdon DATE DEFAULT now() NOT NULL,
  updatedon DATE
);